const tigerReserves = [
  { name: "Nagarjunsagar‑Srisailam Tiger Reserve (AP/Telangana)", lat: "16.3000", lng: "79.1000", details: "Largest tiger reserve by area." },
  { name: "Papikonda Tiger Reserve (AP)", lat: "18.5000", lng: "82.5000", details: "Known for its diverse habitats." },
  { name: "Namdapha Tiger Reserve (Arunachal Pradesh)", lat: "27.8500", lng: "96.4500", details: "India’s largest tiger reserve." },
  { name: "Manas Tiger Reserve (Assam)", lat: "26.7500", lng: "90.5000", details: "A UNESCO World Heritage Site." },
  { name: "Nameri Tiger Reserve (Assam)", lat: "26.5000", lng: "92.0000", details: "Rich in biodiversity." },
  { name: "Dibru‑Saikhowa Tiger Reserve (Assam)", lat: "27.0000", lng: "94.5000", details: "Noted for its riverine ecosystem." },
  { name: "Kaziranga Tiger Reserve (Assam)", lat: "26.5775", lng: "93.1711", details: "Recently added to boost translocation efforts." },
  { name: "Valmiki Tiger Reserve (Bihar)", lat: "24.0000", lng: "84.0000", details: "Also designated as a biosphere reserve." },
  { name: "Achanakmar Tiger Reserve (Chhattisgarh)", lat: "21.0000", lng: "82.0000", details: "Known for its dry deciduous forests." },
  { name: "Indravati Tiger Reserve (Chhattisgarh)", lat: "20.5000", lng: "81.0000", details: "Houses a significant tiger population." },
  { name: "Kanger Ghati Tiger Reserve (Chhattisgarh)", lat: "20.0000", lng: "81.5000", details: "Renowned for its scenic valleys." },
  { name: "Palamau Tiger Reserve (Jharkhand)", lat: "23.0000", lng: "83.0000", details: "Rich in historical significance." },
  { name: "Betla Tiger Reserve (Jharkhand)", lat: "22.8000", lng: "85.0000", details: "Famous for notable elephant sightings." },
  { name: "Bandipur Tiger Reserve (Karnataka)", lat: "11.6416", lng: "76.5733", details: "Part of the Nilgiri Biosphere Reserve." },
  { name: "Nagarhole Tiger Reserve (Karnataka)", lat: "12.2500", lng: "76.0000", details: "Known for its rugged terrain and wildlife." },
  { name: "Bhadra Tiger Reserve (Karnataka)", lat: "13.2833", lng: "75.7500", details: "Noted for its riverine ecosystem." },
  { name: "Periyar Tiger Reserve (Kerala)", lat: "9.5000", lng: "77.1500", details: "Renowned for its picturesque landscapes." },
  { name: "Kanha Tiger Reserve (Madhya Pradesh)", lat: "22.3347", lng: "80.7690", details: "Inspired Rudyard Kipling’s writings." },
  { name: "Bandhavgarh Tiger Reserve (Madhya Pradesh)", lat: "23.7694", lng: "81.1348", details: "Known for its highest tiger density." },
  { name: "Pench Tiger Reserve (MP)", lat: "21.9300", lng: "79.5600", details: "Straddles the MP–MH border." },
  { name: "Panna Tiger Reserve (Madhya Pradesh)", lat: "24.6500", lng: "80.7833", details: "Celebrated for its successful reintroduction." },
  { name: "Satpura Tiger Reserve (Madhya Pradesh)", lat: "22.1167", lng: "80.6333", details: "Features hilly terrain and diverse flora." },
  { name: "Kuno‑Palpur Tiger Reserve (Madhya Pradesh)", lat: "24.2000", lng: "77.5000", details: "India’s first translocated tiger reserve." },
  { name: "Tadoba Andhari Tiger Reserve (Maharashtra)", lat: "20.0500", lng: "78.3500", details: "Largest tiger reserve in Maharashtra." },
  { name: "Melghat Tiger Reserve (Maharashtra)", lat: "21.5000", lng: "79.8000", details: "Known for its rugged landscape." },
  { name: "Pench Tiger Reserve (MH)", lat: "21.9300", lng: "79.5600", details: "Shares its name with MP’s Pench reserve." },
  { name: "Simlipal Tiger Reserve (Odisha)", lat: "21.5000", lng: "86.5000", details: "Part of a larger national park complex." },
  { name: "Satkosia Tiger Reserve (Odisha)", lat: "20.4167", lng: "84.6333", details: "Famous for its dramatic gorge." },
  { name: "Udanti Tiger Reserve (Odisha)", lat: "20.7333", lng: "84.1500", details: "Home to many endemic species." },
  { name: "Ranthambore Tiger Reserve (Rajasthan)", lat: "26.0175", lng: "76.5026", details: "Iconic for its rugged landscape." },
  { name: "Sariska Tiger Reserve (Rajasthan)", lat: "27.6167", lng: "76.6167", details: "Steeped in historical significance." },
  { name: "Mudumalai Tiger Reserve (Tamil Nadu)", lat: "11.5000", lng: "77.5000", details: "Part of the Nilgiri Biosphere." },
  { name: "Anamalai Tiger Reserve (Tamil Nadu)", lat: "10.0000", lng: "77.3333", details: "Rich in endemic flora and fauna." },
  { name: "Kalakkad Mundanthurai Tiger Reserve (Tamil Nadu)", lat: "8.1333", lng: "77.5333", details: "Known for its cascading waterfalls." },
  { name: "Sathyamangalam Tiger Reserve (Tamil Nadu)", lat: "11.6833", lng: "77.6500", details: "Largest tiger reserve in Tamil Nadu." },
  { name: "Dudhwa Tiger Reserve (Uttar Pradesh)", lat: "28.0167", lng: "80.7167", details: "Critical for regional tiger conservation." },
  { name: "Pilibhit Tiger Reserve (Uttar Pradesh)", lat: "28.6167", lng: "79.8000", details: "Noted for its rich floral diversity." },
  { name: "Jim Corbett Tiger Reserve (Uttarakhand)", lat: "29.5300", lng: "78.7740", details: "India’s first national park & tiger reserve." },
  { name: "Rajaji Tiger Reserve (Uttarakhand)", lat: "29.4000", lng: "77.3500", details: "Renowned for its varied terrain." },
  { name: "Sundarbans Tiger Reserve (West Bengal)", lat: "21.9497", lng: "88.6237", details: "Unique mangrove ecosystem with tigers." }
];
